version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - ../..:/workspaces:cached

        command: sleep infinity

        networks:
            - frontend
            - backend
        
    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        networks:
            - backend

    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - backend

volumes:
    postgres-data:

networks:
  frontend:
  backend:
