[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "1.0.0", features = ["postgres-array"] }
serde = { version = "1.0.207", features = ["derive"] }
